name: eShop - Deploy shared infrastructure

on:
  push:
    branches: [main]
    paths:
      - 'infra/bootstrap.bicep'
      - 'infra/main.bicep'
      - 'infra/modules/**'
      - '.github/workflows/deploy-infra.yml'
      - '.github/workflows/deploy-infrastructure.yml'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

concurrency:
  group: eshop-infrastructure
  cancel-in-progress: false

jobs:
  staging-infrastructure:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/deploy-infrastructure.yml
    with:
      environment: staging
      resource-group: rg-eshop-stg-swe-001
      container-registry: acreshopstgswe001
      location: swedencentral
      region-code: swe
      environment-code: stg
    secrets: inherit

  production-infrastructure:
    needs: staging-infrastructure
    if: ${{ needs.staging-infrastructure.result == 'success' }}
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/deploy-infrastructure.yml
    with:
      environment: production
      resource-group: rg-eshop-prd-swe-001
      container-registry: acreshopprdswe001
      location: swedencentral
      region-code: swe
      environment-code: prd
    secrets: inherit
