name: eShop - Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy-staging:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/cd.yml
    with:
      environment: staging
      resource-group: rg-eshop-stg-swe-001
      container-registry: acreshopstgswe001
      location: swedencentral
      region-code: swe
      environment-code: stg
    secrets: inherit

  deploy-production:
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/cd.yml
    needs: deploy-staging
    with:
      environment: production
      resource-group: rg-eshop-prd-swe-001
      container-registry: acreshopprdswe001
      location: swedencentral
      region-code: swe
      environment-code: prd
    secrets: inherit
