name: eShop - Deploy WebApp

on:
  push:
    branches: [main]
    paths:
      - 'src/WebApp/**'
      - 'src/WebAppComponents/**'
      - 'src/EventBus/**'
      - 'src/EventBusRabbitMQ/**'
      - 'src/eShop.ServiceDefaults/**'
      - 'azure.yaml'
      - 'infra/azd/**'
      - 'Directory.Build.props'
      - 'Directory.Build.targets'
      - 'Directory.Packages.props'
      - 'global.json'
      - 'nuget.config'
      - '.dockerignore'
  pull_request:
    branches: [main]
    paths:
      - 'src/WebApp/**'
      - 'src/WebAppComponents/**'
      - 'src/EventBus/**'
      - 'src/EventBusRabbitMQ/**'
      - 'src/eShop.ServiceDefaults/**'
      - 'azure.yaml'
      - 'infra/azd/**'
      - 'Directory.Build.props'
      - 'Directory.Build.targets'
      - 'Directory.Packages.props'
      - 'global.json'
      - 'nuget.config'
      - '.dockerignore'
      - '.github/workflows/template-build-service.yml'
      - '.github/workflows/template-deploy-service.yml'
      - '.github/workflows/template-run-e2e-tests.yml'
      - '.github/workflows/deploy-webapp.yml'
      - '.github/workflows/deploy-all.yml'
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

concurrency:
  group: eshop-deploy-webapp
  cancel-in-progress: false

jobs:
  build:
    permissions:
      contents: read
      checks: write
      code-quality: write
      pull-requests: read
    uses: ./.github/workflows/template-build-service.yml
    with:
      service: webapp

  staging:
    needs: build
    if: ${{ github.event_name != 'pull_request' }}
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/template-deploy-service.yml
    with:
      environment: staging
      resource-group: rg-eshop-stg-swe-001
      container-registry: acreshopstgswe001
      location: swedencentral
      region-code: swe
      environment-code: stg
      service: webapp
      image-tag: ${{ github.sha }}
    secrets: inherit

  staging-e2e:
    needs: staging
    if: ${{ github.event_name != 'pull_request' }}
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/template-run-e2e-tests.yml
    secrets: inherit

  production:
    needs: staging-e2e
    if: ${{ github.event_name != 'pull_request' && needs.staging-e2e.result == 'success' }}
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/template-deploy-service.yml
    with:
      environment: production
      resource-group: rg-eshop-prd-swe-001
      container-registry: acreshopprdswe001
      location: swedencentral
      region-code: swe
      environment-code: prd
      service: webapp
      image-tag: ${{ github.sha }}
    secrets: inherit
